#!/usr/bin/python3

import requests

HOSTNAME = "localhost"
PORT = "8080"

url = "http://" + HOSTNAME + ":" + PORT + "/cfginfo"

response = requests.get(url)

if(response.status_code == 200):
    return_data = response.json()
    for confile in return_data["files"]:
        print(confile)
