#!/usr/bin/python3

import requests

HOSTNAME = "localhost"
PORT = "8080"

url = "http://" + HOSTNAME + ":" + PORT + "/destroyall"

response = requests.delete(url)

if(response.status_code == 200):
    print("Success")

